// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmud_NcdAOxO2VIePiU6JCOZhfROycfbM',
    appId: '1:860139097178:web:c8e09c0a0f6ede52be5c63',
    messagingSenderId: '860139097178',
    projectId: 'minisem5',
    authDomain: 'minisem5.firebaseapp.com',
    storageBucket: 'minisem5.appspot.com',
    measurementId: 'G-7VD65ZLTD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkvr-tHR0NiI1iXum_ObY8FLV6wHs4chU',
    appId: '1:860139097178:android:7494c2812e20f69cbe5c63',
    messagingSenderId: '860139097178',
    projectId: 'minisem5',
    storageBucket: 'minisem5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJU0DwOCUm12ICFufgEw-ZQqRfFqnSiVc',
    appId: '1:860139097178:ios:39aef44ba1738889be5c63',
    messagingSenderId: '860139097178',
    projectId: 'minisem5',
    storageBucket: 'minisem5.appspot.com',
    iosBundleId: 'com.example.miniSem5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJU0DwOCUm12ICFufgEw-ZQqRfFqnSiVc',
    appId: '1:860139097178:ios:39aef44ba1738889be5c63',
    messagingSenderId: '860139097178',
    projectId: 'minisem5',
    storageBucket: 'minisem5.appspot.com',
    iosBundleId: 'com.example.miniSem5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmud_NcdAOxO2VIePiU6JCOZhfROycfbM',
    appId: '1:860139097178:web:64a9d48ecd291bdabe5c63',
    messagingSenderId: '860139097178',
    projectId: 'minisem5',
    authDomain: 'minisem5.firebaseapp.com',
    storageBucket: 'minisem5.appspot.com',
    measurementId: 'G-YSXCJ5Z9PG',
  );
}
